# #####################
# sparta makefile
# written by mkxzy & MoonWolf
# 2018-4-8
# #####################

.PHONY: clean

outdir=bin
name=sparta

build:
	go build -o $(outdir)/$(name)

clean:
	rm -rf $(outdir)
